### ISSUE TITLE
toString method on UltimateTicTacToe has a bug when showing a board with a winning row

### ISSUE THREAD

**Issue by Nicolasara** [Nicolasara/UltimateTicTacToeAI#7]
After finishing a game the ultimate board is incorrectly shown. It seems like the columns are not placed properly. 

![gameOverBug](https://github.com/Nicolasara/UltimateTicTacToeAI/assets/75596123/fd03af82-7c19-43a2-bcad-1cccc739b75f)

**Comment by huntergroff** [comment]
Will take a look at this now
